insert into user values(21, sysdate(), 'preety', sysdate(), sysdate())
insert into user values(22, sysdate(), 'heena', sysdate(), sysdate())
insert into user values(23, sysdate(), 'parakh', sysdate(), sysdate())
insert into post values(1, 'this is first post', 22)
insert into post values(2, 'this is second post', 22)
insert into post values(3, 'this is first post', 23)